### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by yhenon** [deepcam-cn/FaceQuality#1]
Thanks for sharing this very interesting work. Right now, no license has been included in the repo, meaning all rights are reserved (https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license), and it cannot be used by others. 

Could you perhaps consider including some form of open-source license?

**Comment by wjtan99** [comment]
Hi, we added MIT license on the page.  
Thanks for your reminder.

**Comment by yhenon** [comment]
Thank you!
